/* Generated By:JJTree: Do not edit this line. ASTFunctionStmt.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package analyzer.ast;

public
class ASTFunctionStmt extends SimpleNode {
  public ASTFunctionStmt(int id) {
    super(id);
  }

  public ASTFunctionStmt(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3be43d4aa8dd02a77a43337a97417c88 (do not edit this line) */
