/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 7.0.2 */
package analyzer.ast;

public interface ParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTVOID = 1;
  public int JJTASSIGNSTMT = 2;
  public int JJTWHILESTMT = 3;
  public int JJTWHILECOND = 4;
  public int JJTWHILEBLOCK = 5;
  public int JJTDOWHILESTMT = 6;
  public int JJTIFSTMT = 7;
  public int JJTIFCOND = 8;
  public int JJTIFBLOCK = 9;
  public int JJTELSEBLOCK = 10;
  public int JJTFORSTMT = 11;
  public int JJTRETURNSTMT = 12;
  public int JJTFUNCTIONSTMT = 13;
  public int JJTLOGIC = 14;
  public int JJTCOMPARE = 15;
  public int JJTADDITION = 16;
  public int JJTMULTI = 17;
  public int JJTMINUS = 18;
  public int JJTNOT = 19;
  public int JJTIDENTIFIER = 20;
  public int JJTINTVALUE = 21;
  public int JJTREALVALUE = 22;


  public String[] jjtNodeName = {
    "Program",
    "void",
    "AssignStmt",
    "WhileStmt",
    "WhileCond",
    "WhileBlock",
    "DoWhileStmt",
    "IfStmt",
    "IfCond",
    "IfBlock",
    "ElseBlock",
    "ForStmt",
    "ReturnStmt",
    "FunctionStmt",
    "Logic",
    "Compare",
    "Addition",
    "Multi",
    "Minus",
    "Not",
    "Identifier",
    "IntValue",
    "RealValue",
  };
}
/* JavaCC - OriginalChecksum=9c624f02d42cc959895847b86a53213b (do not edit this line) */
