/* Generated By:JavaCC: Do not edit this line. ParserVisitor.java Version 7.0.2 */
package analyzer.ast;

public interface ParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTProgram node, Object data);
  public Object visit(ASTAssignStmt node, Object data);
  public Object visit(ASTWhileStmt node, Object data);
  public Object visit(ASTWhileCond node, Object data);
  public Object visit(ASTWhileBlock node, Object data);
  public Object visit(ASTDoWhileStmt node, Object data);
  public Object visit(ASTIfStmt node, Object data);
  public Object visit(ASTIfCond node, Object data);
  public Object visit(ASTIfBlock node, Object data);
  public Object visit(ASTElseBlock node, Object data);
  public Object visit(ASTForStmt node, Object data);
  public Object visit(ASTReturnStmt node, Object data);
  public Object visit(ASTFunctionStmt node, Object data);
  public Object visit(ASTLogic node, Object data);
  public Object visit(ASTCompare node, Object data);
  public Object visit(ASTAddition node, Object data);
  public Object visit(ASTMulti node, Object data);
  public Object visit(ASTMinus node, Object data);
  public Object visit(ASTNot node, Object data);
  public Object visit(ASTIdentifier node, Object data);
  public Object visit(ASTIntValue node, Object data);
  public Object visit(ASTRealValue node, Object data);
}
/* JavaCC - OriginalChecksum=bf4e64f5b98db89b4c01f1f9900d544a (do not edit this line) */
