- hosts: aws_ec2_standalone
  become: yes
  tasks:
    - name: Update and upgrade packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install required dependencies
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - mysql-server
        - sysbench
        - python3-pymysql

    - name: Ensure MySQL server is running
      service:
        name: mysql
        state: started

    - name: Create root user with password
      shell: |
        mysql -u root -proot -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root';"

    - name: Create database, user, and grant privileges
      shell: |
        mysql -u root -proot -e "CREATE DATABASE IF NOT EXISTS projet;"
        mysql -u root -proot -e "CREATE USER IF NOT EXISTS 'ubuntu'@'localhost' IDENTIFIED BY 'ubuntu';"
        mysql -u root -proot -e "GRANT ALL PRIVILEGES ON *.* TO 'ubuntu'@'localhost' WITH GRANT OPTION;"
        mysql -u root -proot -e "FLUSH PRIVILEGES;"

    - name: Create shared directory
      file:
        path: /home/shared
        state: directory

    - name: Set permissions for shared directory
      file:
        path: /home/shared
        mode: '0777'
        recurse: yes

    - name: Download Sakila database example using curl
      command: "curl -o /home/shared/sakila-db.tar.gz https://downloads.mysql.com/docs/sakila-db.tar.gz"

    - name: Extract Sakila database
      unarchive:
        src: "/home/shared/sakila-db.tar.gz"
        dest: "/home/shared/"
        remote_src: yes

    - name: Import Sakila schema
      community.mysql.mysql_db:
       login_user: root
       login_password: root
       state: import
       name: sakila
       target: /home/shared/sakila-db/sakila-schema.sql

    - name: Import Sakila data
      community.mysql.mysql_db:
       login_user: root
       login_password: root
       state: import
       name: sakila
       target: /home/shared/sakila-db/sakila-data.sql

    - name: Show full tables
      community.mysql.mysql_query:
       login_user: root
       login_password: root
       login_db: sakila
       query: SHOW FULL TABLES

    - name: Count films
      community.mysql.mysql_query:
       login_user: root
       login_password: root
       login_db: sakila
       query: SELECT COUNT(*) FROM film

    - name: Count film texts
      community.mysql.mysql_query:
       login_user: root
       login_password: root
       login_db: sakila
       query: SELECT COUNT(*) FROM film_text
