/* Generated By:JJTree: Do not edit this line. ASTFunctionStmt.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package analyzer.ast;

public
class ASTFunctionStmt extends SimpleNode {
    public ASTFunctionStmt(int id) {
        super(id);
    }

    public ASTFunctionStmt(Parser p, int id) {
        super(p, id);
    }


    /** Accept the visitor. **/
    public Object jjtAccept(ParserVisitor visitor, Object data) {

        return
                visitor.visit(this, data);
    }
    private String m_value = null;
    public void setValue(String v) { m_value = v; }
    public String getValue() { return m_value; }
}
/* JavaCC - OriginalChecksum=f508d1449faf6c23e99fcd9cf6d0a21b (do not edit this line) */
